### ISSUE TITLE
Cannot run Loboevolution from Eclipse 

### ISSUE THREAD

**Issue by sudo-apt-get-install** [oswetto/Loboevolution#10]
Eclipse Neon 
Java 1.8_92 
Latest code as of [Commit #544](https://github.com/oswetto/Loboevolution/commit/6128712dd754c4b8a814d36a9dca29108e473125)
Running EntryPoint.java as a Java Application
Window comes up but no text

**Comment by oswetto** [comment]
Hello sudo-apt-get-install, you need to set up the "ext.dirs" property. 

Step1: run build.xml
Step2: In main method of EntryPoint set "ext.dirs"   
System.setProperty("ext.dirs","C://tmp//lobo-build//lobo-0.99.1//ext"); // Change path with your path
ReuseManager.getInstance().launch(args);
