### ISSUE TITLE
Links 

### ISSUE THREAD

**Issue by LeiphiDev1** [oswetto/LoboEvolution#16]
Links are not working for me.
The cursor dont change and i can not click the link to open it.

**Comment by oswetto** [comment]
Fixed, please, can you try again?

**Comment by LeiphiDev1** [comment]
NO
This is the correct version https://sourceforge.net/projects/loboevolution/ right?
And the site don't display correctly.
I cant find the file for the css display attribute rendering can you say it?

**Comment by oswetto** [comment]
If you want to test my last commit, download the code from the "clone or download" button or use git for the payment code from "https://github.com/oswetto/LoboEvolution.git". 
Run LoboEvolution/build.xml with apache ant to generate executable jar.
In Sourceforge I release only the stable version
