### ISSUE TITLE
Be able to write to disk from Java code called from JavaScript (ie for saving LocalStorage to disk)

### ISSUE THREAD

**Issue by ethan2-0** [oswetto/LoboEvolution#2]
It would be useful to be able to save localStorage to disk in order to comply with the spec (that says it should be updated promptly). This is currently impossible due to our JavaScript code sandboxing model.

I think the easiest way to implement this would be to have a worker thread that polls for tasks every 1sec and does the writing; that way, we can just queue a task from the localStorage implementation. Given the nature of Java's sandboxing model, I think another thread is the only way to do this.

**Comment by oswetto** [comment]
For now loboevolution save css and js in sqlite dabase see commit d5547c2
