### ISSUE TITLE
Add missing cursor values

### ISSUE THREAD

**Issue by oswetto** [oswetto/LoboEvolution#22]
style="cursor:auto"
style="cursor:e-resize"
style="cursor:grab"
style="cursor:n-resize"
style="cursor:ne-resize"
style="cursor:nw-resize"
style="cursor:s-resize"
style="cursor:se-resize"
style="cursor:sw-resize"
style="cursor:w-resize"

**Comment by LeiphiDev1** [comment]
Do you habe this ones: wait, help, defaul, crosshair, grabbing?

**Comment by oswetto** [comment]
LoboEvolution alredy support wait, default, crosshair and swing don't support help cursor
