### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by 369David369** [oswetto/LoboEvolution#28]
I've been watching this repo for over a half year. So i know the code quite good. But i dont know what i can do on this project. Is there a todo list?

**Comment by oswetto** [comment]
Hi 369David369,
thanks for your time, you can see [How to do](https://github.com/oswetto/LoboEvolution/wiki/How-To)
At the moment there is not a list of things to do. Many css3 are not supported for example the "box-sizing" property, I have only added the binding. Support for CANVAS and SVG tags is minimal, the AUDIO and VIDEO html tags are not supported
