### ISSUE TITLE
JavaDoc for Add ons?

### ISSUE THREAD

**Issue by 369David369** [oswetto/LoboEvolution#39]
I like the Add on Api from Lobo. But it is not user friendly and time consuming to make Plugins.
A JavaDoc would be extremly useful.

If you dont know what a JavaDoc is here is a small Summary. It is a Program from Orakle/Sun what converts java source code into html documentation. Here is an example: https://hub.spigotmc.org/javadocs/spigot/ it is a Minecraft Server plugin Api.

**Comment by oswetto** [comment]
Yuo can find loboevolution javadoc here: https://oswetto.github.io/LoboEvolution/.
If you want add plugin in LoboEvolution you can read this article https://dzone.com/articles/plugging-lobos-pure-java-web-b

**Comment by 369David369** [comment]
Okay cool!
