### ISSUE TITLE
cannot find symbol: import org.lobobrowser.html.control.RCanvasControl;

### ISSUE THREAD

**Issue by asciibox** [oswetto/Loboevolution#4]
Hello,

this class is missing, although a search for RCanvasControl shows that it is getting imported in org.lobobrowser.html.layout.CanvasLayout.java line 18.

![canvascontrol](https://cloud.githubusercontent.com/assets/7685150/7103704/1b44b686-e0b5-11e4-97f4-793ad0b44877.jpg)

Thank you
Oliver

**Comment by oswetto** [comment]
Missing class fix.
