### ISSUE TITLE
Replace System.out with Logger

### ISSUE THREAD

**Issue by oswetto** [oswetto/LoboEvolution#46]
Use java.util.logging.Logger

**Comment by vijayakumarbathini** [comment]
Can I work on this

**Comment by vijayakumarbathini** [comment]
Will be following below article for this implementation

https://examples.javacodegeeks.com/enterprise-java/maven/maven-slf4j-integration-example/

and what is the level you wanted to use for all loggers, believe changes to be done in *.java only as other files are also having System.out

**Comment by oswetto** [comment]
Hi @vijayakumarbathini,
changes must be made in all java files. Replace System.out with logger.info and Sysyem.out in the catch with logger.severe and replace e.printStackTrace () with logger.severe.

Please use only the java logging "java.util.logging.Logger", at the moment maven is only used to call ant-task and to facilitate the compilation of the project to maven users

Thanks :-)

**Comment by vijayakumarbathini** [comment]
I have sent a Pull Request, changed the required system.out in java classes

**Comment by oswetto** [comment]
Hi @vijayakumarbathini,
your pull did not compile, there were errors.
I solved in the last commit. Please compile code before commit :-)
