### ISSUE TITLE
IDE Setup Guide

### ISSUE THREAD

**Issue by ajinkyakulkarni** [oswetto/Loboevolution#5]
Is there any documentation available on how to setup this project using Netbeans/Eclipse/ IntelliJ IDEA?

**Comment by oswetto** [comment]
1. In eclipse create Modules
- Common
- HTML_Renderer
- izPack_RegistryPanel
- Platform_Core
- Platform_Public_API
- Primary_Extension
- Testing
- XAMJ_Build
- parser/src/main

2. HTML_Renderer depends from Common and parser projects and from libraries batik, jdatapicker and xalan(you can find lib in XAMJ_Build/ext)
3. izPack_RegistryPanel depends from libraries compiler and jRegestry(you can find lib in XAMJ_Build)
4. Platform_Core depends from Common and Platform_Public_API projects
5. Platform_Public_API depends from Common project
6. Primary_Extension depends from Common, HTML_Renderer, Platform_Core, Platform_Public_API projects and PDFRender library(you can find lib in XAMJ_Build/ext)
7. Testing depends from all projects
