### ISSUE TITLE
Tow issue found: CookieStore.getCookiesStrict() and Rhino source

### ISSUE THREAD

**Issue by zhudizhudi** [oswetto/Loboevolution#7]
Hi there 
seems I find two bugs in the source
a. org.lobobrowser.request.CookieStore.getCookiesStrict()
In this method the following source need to declare inside the while loop not 
outside it:
line 333 Cookie cookie_value = new Cookie(); 
unless the collection will only edit the same cookie repeatedly

b. I think the Rhino  is not updated to newest version OR　some source is changed to wrong like:
org.mozilla.javascript.NativeError
It cost me 2 days to find the reason..

And I am looking into your source and need your help on some difficult case.
My email is zhudizhudizhudi@hotmail.com OR you can let me know your available contact
Thank you very much
Ｇrazie　！

Best Regards
Joedy from Shanghai

**Comment by oswetto** [comment]
Hello Joedy,
at moment i don't have time to update Lobo Evolution, if you can, fork project and create pullrequest with the fix. Mozilla Rhino is updated at version 1.7.7.1. You can contact me at this mail: ivan.difrancesco@yahoo.it

Ivan

**Comment by zhudizhudi** [comment]
Hi Ivan

Thank you very much for you reply.

I can help to fix the bug when I have time later.

Actually I am trying to create the HttpRequest text (not by browser) to visit some website like  the Robot action by java.
I referred you great work and created the httprequest with session, cockie, token id etc.
But got problem at javascript calling.

The problem is like I can only get the javascript but
separated from the homepage using HttpRequest, So when using it to run in the java source using Rhino the element based on the html page will be missing.

One example is like, below is a small javascript code which the website homepage is using, but when you using java to run the js,
some var related to the homepage can not be recognized, just like "document" in red.
(function () {

    var myDate = new Date();
    var timestamp = new Date().getTime();
    //$("#token").val(timestamp);


    _fmOpt = {
        bd: true,
        partner: 'damai',
        appName: 'damai_web',
        token: timestamp
    };

    var cimg = new Image(1, 1);
    cimg.onload = function () {
        _fmOpt.imgLoaded = true;
    };
    cimg.src = "https://fp.fraudmetrix.cn/fp/clear.png?partnerCode=" + _fmOpt.partner + "&appName=" + _fmOpt.appName + "&tokenId=" + _fmOpt.token;
    var fp = document.createElement('script');
    fp.type = 'text/javascript';
    fp.async = true;
    fp.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'static.fraudmetrix.cn/fm.js?ver=0.1';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(fp, s);

})();

My question is when I send a Httprequest to a website and got back the homepage html and separatedly also got the javascript file.
How can I run the javascript file in the homepage html framework just like the webbrowser is doing.
I believe you webbrowser is doing it but I can not find the flow of doing so by reviewing the source.

For example, you use the following code to create the js scope instead of using Scriptable scope = ctx.initStandardObjects();
In HTMLAbstractUIElement.java of package org.lobobrowser.html.domimpl;

Document doc = this.document;
                    if (doc == null) {
                        throw new IllegalStateException("Element does not belong to a document.");
                    }
                    Context ctx = Executor.createContext(this.getDocumentURL(), uac);
                    try {
                        Scriptable scope = (Scriptable) doc.getUserData(Executor.SCOPE_KEY);
                        if (scope == null) {
                            throw new IllegalStateException(
                                    "Scriptable (scope) instance was expected to be keyed as UserData to document using "
                                            + Executor.SCOPE_KEY);
                        }
                        Scriptable thisScope = (Scriptable) JavaScript.getInstance().getJavascriptObject(this, scope);
                        try {
                            // TODO: Get right line number for script. //TODO:
                            // Optimize this in case it's called multiple times?
                            // Is that done?
                            f = ctx.compileFunction(thisScope, functionCode,
                                    this.getTagName() + "[" + this.getId() + "]." + attributeName, 1, null);

I just not quite no how you create the context and scope of the js running.

Hope I explained the question clearly and let me know if you got puzzled

Grazie
Joedy 



 
 
------------------ Original ------------------

**Comment by oswetto** [comment]
Hello jody i create scope in this line: 
Scriptable scope = (Scriptable) doc.getUserData(Executor.SCOPE_KEY); 
and at this line create context
UserAgentContext uac = this.getUserAgentContext();
Context ctx = Executor.createContext(this.getDocumentURL(), uac);

For your example i think yuo can use standard initStandardObjects()
At this link i have create a simply example how mozilla run javascript: https://github.com/oswetto/Loboevolution/tree/master/Testing/src/main/java/org/lobobrowser/html/jstest

**Comment by zhudizhudi** [comment]
Hello Ivan

Thank you very much for your reply. and thank for the example code.

I am sorry maybe I am not explained my question clearly.

For example I want to run the javascript below and
This javascript is based on a website homepage.

function() {
    
    m = window.console,
    n = window.navigator,
    o = window.document,
    p = n.userAgent,
       
        };

I can run the javascript by java Rhino but the error message is like:
"Javascript error at _$Id:1: ReferenceError: "window" is not defined. (_$Id#1)"

My question is how can I let Rhino know the window object ( it is based on the homepage window opened by browser)  ?

Will be very much appreciated you can let me know a short flow of how you create a window object and doc object and based on it to create
the context, scope for javascript to run and refer to.

Thank you very much
Joedy


 
 
------------------ Original ------------------

**Comment by oswetto** [comment]
RunJavascriptWindow example: https://github.com/oswetto/Loboevolution/blob/master/Testing/src/main/java/org/lobobrowser/html/jstest/RunJavascriptWindow
