### ISSUE TITLE
Building with Ant fails

### ISSUE THREAD

**Issue by dvaosta** [oswetto/Loboevolution#9]
I've tried to run the build.xml ant file from inside eclipse, but I get this error:
BUILD FAILED
D:\my_user\eclipse_projects\browser\Loboevolution\XAMJ_Build\build.xml:116: destination directory "D:\my_user\eclipse_projects\browser\Loboevolution\IzPack_RegistryPanel\bin" does not exist or is not a directory

**Comment by oswetto** [comment]
Hello dvaosta, 
in your eclipse properties for IzPack_RegistryPanel you have added output folder?

![output](https://cloud.githubusercontent.com/assets/6113075/21850671/06f543a8-d80c-11e6-8694-035b4d38fe8b.png)

Please, repeat thi operation for all project.
